<?xml version="1.0" encoding="utf-8"?><Database Name="dbTomoca" Class="TomocaMoviesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=dbTomoca;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TomocaMoviesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Actors" Member="Actors">
    <Type Name="Actor">
      <Column Name="ActorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Actor_MovieActor" Member="MovieActors" ThisKey="ActorID" OtherKey="ActorID" Type="MovieActor" />
    </Type>
  </Table>
  <Table Name="dbo.YoutubeReviews" Member="YoutubeReviews">
    <Type Name="YoutubeReview">
      <Column Name="YoutubeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Video" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="YoutubeReview_ReviewOfMovie" Member="ReviewOfMovies" ThisKey="YoutubeID" OtherKey="YoutubeID" Type="ReviewOfMovie" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Member="City1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="City_MovieTheater" Member="MovieTheaters" ThisKey="CityID" OtherKey="CityID" Type="MovieTheater" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Movy_Comment" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
      <Association Name="User_Comment" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Content" Member="Contents">
    <Type Name="Content">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="New_Content" Member="New" ThisKey="NewsID" OtherKey="NewsID" Type="New" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Directors" Member="Directors">
    <Type Name="Director">
      <Column Name="DirectorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Director_MovieDirector" Member="MovieDirectors" ThisKey="DirectorID" OtherKey="DirectorID" Type="MovieDirector" />
    </Type>
  </Table>
  <Table Name="dbo.Genres" Member="Genres">
    <Type Name="Genre">
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenreName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_MoviesGenre" Member="MoviesGenres" ThisKey="GenreID" OtherKey="GenreID" Type="MoviesGenre" />
    </Type>
  </Table>
  <Table Name="dbo.LocateMovie" Member="LocateMovies">
    <Type Name="LocateMovie">
      <Column Name="TicketID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Locate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LocateMovie_Ticket" Member="Ticket" ThisKey="TicketID" OtherKey="TicketID" Type="Ticket" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.MovieActor" Member="MovieActors">
    <Type Name="MovieActor">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ActorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Actor_MovieActor" Member="Actor" ThisKey="ActorID" OtherKey="ActorID" Type="Actor" IsForeignKey="true" />
      <Association Name="Movy_MovieActor" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovieDirector" Member="MovieDirectors">
    <Type Name="MovieDirector">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DirectorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Director_MovieDirector" Member="Director" ThisKey="DirectorID" OtherKey="DirectorID" Type="Director" IsForeignKey="true" />
      <Association Name="Movy_MovieDirector" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movy">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Plot" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ReleaseYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMDb" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Tomatometer" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AudienceScore" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Trailer" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TimeOfFilm" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Banner" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UpComming" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Movy_Comment" Member="Comments" ThisKey="MovieID" OtherKey="MovieID" Type="Comment" />
      <Association Name="Movy_MovieActor" Member="MovieActors" ThisKey="MovieID" OtherKey="MovieID" Type="MovieActor" />
      <Association Name="Movy_MovieDirector" Member="MovieDirectors" ThisKey="MovieID" OtherKey="MovieID" Type="MovieDirector" />
      <Association Name="Movy_MoviesGenre" Member="MoviesGenres" ThisKey="MovieID" OtherKey="MovieID" Type="MoviesGenre" />
      <Association Name="Movy_MoviesVote" Member="MoviesVotes" ThisKey="MovieID" OtherKey="MovieID" Type="MoviesVote" />
      <Association Name="Movy_ReviewOfMovie" Member="ReviewOfMovies" ThisKey="MovieID" OtherKey="MovieID" Type="ReviewOfMovie" />
      <Association Name="Movy_ShowTimeMovie" Member="ShowTimeMovies" ThisKey="MovieID" OtherKey="MovieID" Type="ShowTimeMovie" />
      <Association Name="Movy_Ticket" Member="Tickets" ThisKey="MovieID" OtherKey="MovieID" Type="Ticket" />
    </Type>
  </Table>
  <Table Name="dbo.MoviesGenres" Member="MoviesGenres">
    <Type Name="MoviesGenre">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Genre_MoviesGenre" Member="Genre" ThisKey="GenreID" OtherKey="GenreID" Type="Genre" IsForeignKey="true" />
      <Association Name="Movy_MoviesGenre" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoviesVote" Member="MoviesVotes">
    <Type Name="MoviesVote">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Action" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Movy_MoviesVote" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
      <Association Name="User_MoviesVote" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovieTheater" Member="MovieTheaters">
    <Type Name="MovieTheater">
      <Column Name="TheaterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TheaterName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="MovieTheater_ShowTimeMovie" Member="ShowTimeMovies" ThisKey="TheaterID" OtherKey="TheaterID" Type="ShowTimeMovie" />
      <Association Name="MovieTheater_Ticket" Member="Tickets" ThisKey="TheaterID" OtherKey="TheaterID" Type="Ticket" />
      <Association Name="City_MovieTheater" Member="City" ThisKey="CityID" OtherKey="CityID" Type="City" IsForeignKey="true" />
      <Association Name="Theater_MovieTheater" Member="Theater" ThisKey="Type" OtherKey="TheaterID" Type="Theater" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="NewsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReadCount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="New_Content" Member="Content" ThisKey="NewsID" OtherKey="NewsID" Type="Content" Cardinality="One" />
      <Association Name="User_New" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReviewOfMovie" Member="ReviewOfMovies">
    <Type Name="ReviewOfMovie">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="YoutubeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Movy_ReviewOfMovie" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
      <Association Name="YoutubeReview_ReviewOfMovie" Member="YoutubeReview" ThisKey="YoutubeID" OtherKey="YoutubeID" Type="YoutubeReview" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SetShowTime" Member="SetShowTimes">
    <Type Name="SetShowTime">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ShowTime_SetShowTime" Member="ShowTime" ThisKey="TimeID" OtherKey="TimeID" Type="ShowTime" IsForeignKey="true" />
      <Association Name="ShowTimeMovie_SetShowTime" Member="ShowTimeMovie" ThisKey="ID" OtherKey="ID" Type="ShowTimeMovie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShowTime" Member="ShowTimes">
    <Type Name="ShowTime">
      <Column Name="TimeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ShowTime_SetShowTime" Member="SetShowTimes" ThisKey="TimeID" OtherKey="TimeID" Type="SetShowTime" />
    </Type>
  </Table>
  <Table Name="dbo.ShowTimeMovie" Member="ShowTimeMovies">
    <Type Name="ShowTimeMovie">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TheaterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ShowTimeMovie_SetShowTime" Member="SetShowTimes" ThisKey="ID" OtherKey="ID" Type="SetShowTime" />
      <Association Name="Movy_ShowTimeMovie" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
      <Association Name="MovieTheater_ShowTimeMovie" Member="MovieTheater" ThisKey="TheaterID" OtherKey="TheaterID" Type="MovieTheater" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Theater" Member="Theaters">
    <Type Name="Theater">
      <Column Name="TheaterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Theater" Member="Theater1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Theater_MovieTheater" Member="MovieTheaters" ThisKey="TheaterID" OtherKey="Type" Type="MovieTheater" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="TicketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TicketNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TicketAvailable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TheaterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Money" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_UserBook" Member="UserBooks" ThisKey="TicketID" OtherKey="TicketID" Type="UserBook" />
      <Association Name="LocateMovie_Ticket" Member="LocateMovie" ThisKey="TicketID" OtherKey="TicketID" Type="LocateMovie" IsForeignKey="true" />
      <Association Name="Movy_Ticket" Member="Movy" ThisKey="MovieID" OtherKey="MovieID" Type="Movy" IsForeignKey="true" />
      <Association Name="MovieTheater_Ticket" Member="MovieTheater" ThisKey="TheaterID" OtherKey="TheaterID" Type="MovieTheater" IsForeignKey="true" />
      <Association Name="TicketType_Ticket" Member="TicketType" ThisKey="TicketID" OtherKey="TicketID" Type="TicketType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TicketType" Member="TicketTypes">
    <Type Name="TicketType">
      <Column Name="TicketID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VIP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Student" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Child" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TicketType_Ticket" Member="Ticket" ThisKey="TicketID" OtherKey="TicketID" Type="Ticket" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.UserBook" Member="UserBooks">
    <Type Name="UserBook">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TicketID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Ticket_UserBook" Member="Ticket" ThisKey="TicketID" OtherKey="TicketID" Type="Ticket" IsForeignKey="true" />
      <Association Name="User_UserBook" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Permission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Comment" Member="Comments" ThisKey="UserID" OtherKey="UserID" Type="Comment" />
      <Association Name="User_MoviesVote" Member="MoviesVotes" ThisKey="UserID" OtherKey="UserID" Type="MoviesVote" />
      <Association Name="User_New" Member="News" ThisKey="UserID" OtherKey="UserID" Type="New" />
      <Association Name="User_UserBook" Member="UserBooks" ThisKey="UserID" OtherKey="UserID" Type="UserBook" />
    </Type>
  </Table>
</Database>